name: to_yaml
description: A simple command-line application.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  yaml: any
  test: any