name: to_yaml
description: Simple package to generate yaml from Map.
version: 0.0.2
homepage: https://github.com/smgks/to_yaml

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  yaml: any
  test: any