name: to_yaml
description: Simple package to generate yaml from Map.
version: 0.0.3
homepage: https://github.com/smgks/to_yaml

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  yaml: 2.2.1
  test: 1.15.3